config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  resources :sessions, except: [:index, :new, :destroy]
  
  resources :users, except: [:index]
  
  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def is_login?
    if !session[:user_id]
      redirect_to login_path
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :task
  has_many :project_user
  has_many :joinuser, through: :project_user, source: :user
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  
  STATUS_OPTIONS = {1 => "未着手", 2 => "処理中", 3 => "レビュー中", 4 => "完了"}
  PRIORITY_OPTIONS = {1 => "緊急", 2 => "高", 3 => "中", 4 => "低"}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :project
  has_many :task
  has_many :project_user
  has_many :myproject, through: :project_user, source: :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def is_login?
    if !session[:user_id]
      redirect_to login_path
    end
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = current_user.myproject
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_param)
    @project.user_id = current_user.id
    
    # transaction
    result = false
    ActiveRecord::Base.transaction do
      @project.save!
      @project_user = ProjectUser.new(user_id: current_user.id, project_id: @project.id)
      @project_user.save!
      result = true
    end
    
    if result
      redirect_to projects_path, success: "プロジェクトを登録しました。"
    else
      render plain: "error"
    end
  
  end

  def show
    @project = current_user.myproject.find(params[:id])
    @tasks =  Task.where(project_id: @project.id, user_id: current_user.id)
  end
  
  private
  def project_param
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email])
    if !@user.nil? && @user.authenticate(params[:session][:password])
      # sessionに保存
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), success: 'ログインしました'
    else 
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
    
  end
  
  
  def destroy
    session[:user_id] = nil
    
    redirect_to login_path, success: 'ログアウトしました'
  
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    
  end
  
  def new
    @task = Task.new
    # プロジェクト内のユーザ
    @users = current_project.joinuser
  end
  
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.project_id = params[:project_id]
    
    if @task.save
      render plain: "success"
    else
      render plain: @task.errors
    end
  end
  
  def update
    
  end
  
  def destroy
    
  end
  
  private
  def current_project
    @current_project ||= Project.find(params[:project_id])
  end
  
  def task_params
    params.require(:task).permit(:title, :body, :start_date, :end_date, :status, 
    :priority, :assign, :project_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_login?, only: [:show]
  
  def index
    @user = User.new
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_param)
    if @user.save
      redirect_to user_path(@user.id), success: 'ようこそ、miniscrumへ'
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  def show
    
    render plain: "show"
  end
  
  private
  def user_param
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniscram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<%= link_to '新規作成', new_project_path %>

<ul>
<% @projects.each do |p| %>
  <li><%= link_to p.name, project_path(p) %></li>
<% end %>
</ul>

app/views/projects/new.html.erb
<%= form_for @project do |f| %>
  name : <%= f.text_field :name %>
  description : <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<%= link_to "タスク作成", new_project_task_path(@project) %>

<table>
  <tr>
    <td>名前</td><td><%= @project.name %></td>
  </tr>
  <tr>
    <td>詳細</td><td><%= @project.description %></td>
  </tr>
</table>


<h2>タスク一覧</h2>
<% if !@tasks.empty? %>
  <ul>
    <% @tasks.each do |t| %>
    <li><%= t.name %></li>
    <% end %>
  </ul>
<% end %>

app/views/tasks/new.html.erb
<h1>タスク新規作成</h1>

<%= form_for @task, url: project_tasks_path  do |f| %>
  タイトル : <%= f.text_field :title %> <br>
  本文 : <%= f.text_field :body %><br>
  開始 : <%= f.date_select :start_date %><br>
  終了 : <%= f.date_select :end_date %><br>
  ステータス : <%= f.select :status, Task::STATUS_OPTIONS.invert, { prompt: "選択してください"} %><br>
  優先度 : <%= f.select :priority, Task::PRIORITY_OPTIONS.invert, { prompt: "選択してください"} %><br>
  アサイン : <%= f.select :assign, @users.map{|u| [u.name, u.id]} %><br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  name : <%= f.text_field :name %>
  email : <%= f.text_field :email %>
  password : <%= f.password_field :password %>
  
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<ul>
<%= @project.each do |p| %>
<li><%= p.name %></li>
<% end %>
</ul>